# Generated by Django 5.2.5 on 2025-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_uz',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
