# Generated by Django 5.2.5 on 2025-08-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
