# Generated by Django 5.2.5 on 2025-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_price_product_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimages',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
