# Generated by Django 5.2.5 on 2025-08-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_categoryimages_is_main_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='old_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='price',
        ),
    ]
