# Generated by Django 5.2.5 on 2025-09-01 14:16

import app.user.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_discount_price_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimages',
            name='image',
            field=models.ImageField(upload_to='images/category/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif', 'avif']), app.user.validations.check_image_size]),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(upload_to='images/product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif']), app.user.validations.check_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heic', 'heif']), app.user.validations.check_image_size]),
        ),
    ]
