# Generated by Django 5.2.5 on 2025-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_categoryimages_image_alter_productcolor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvalue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
