# Generated by Django 5.2.5 on 2025-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productcolor_price_alter_productvalue_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
