# Generated by Django 5.2.5 on 2025-09-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_name_en_order_name_ru_order_name_uz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
