# Generated by Django 5.2.5 on 2025-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
