# Generated by Django 5.2.5 on 2025-09-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_item_price_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_uz',
        ),
    ]
