# Generated by Django 5.2.5 on 2025-08-22 12:34

import app.user.validations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.IntegerField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/banners/', validators=[app.user.validations.check_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('theme', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('type', models.CharField(choices=[('p', 'products'), ('s', 'services'), ('t', 'technology'), ('c', 'company')], max_length=255)),
                ('type_uz', models.CharField(choices=[('p', 'products'), ('s', 'services'), ('t', 'technology'), ('c', 'company')], max_length=255, null=True)),
                ('type_en', models.CharField(choices=[('p', 'products'), ('s', 'services'), ('t', 'technology'), ('c', 'company')], max_length=255, null=True)),
                ('type_ru', models.CharField(choices=[('p', 'products'), ('s', 'services'), ('t', 'technology'), ('c', 'company')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('address_uz', models.CharField(max_length=255, null=True)),
                ('address_en', models.CharField(max_length=255, null=True)),
                ('address_ru', models.CharField(max_length=255, null=True)),
                ('working_time', models.TextField()),
                ('working_time_uz', models.TextField(null=True)),
                ('working_time_en', models.TextField(null=True)),
                ('working_time_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/news/', validators=[app.user.validations.check_image_size])),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.news')),
            ],
        ),
        migrations.CreateModel(
            name='OurContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('our_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='about.ourcontact')),
            ],
        ),
        migrations.CreateModel(
            name='OurContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, validators=[app.user.validations.validate_phone_number])),
                ('our_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='about.ourcontact')),
            ],
        ),
    ]
