# Generated by Django 5.2.5 on 2025-08-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimages',
            options={'verbose_name': 'NewsImage', 'verbose_name_plural': 'NewsImages'},
        ),
    ]
