# Generated by Django 5.2.5 on 2025-08-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_news_options_alter_newsimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.JSONField(default=list),
        ),
    ]
