# Generated by Django 5.2.5 on 2025-08-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='about.news'),
        ),
    ]
