# Generated by Django 5.2.5 on 2025-08-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_image_news_images_alter_newsimages_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImages',
        ),
    ]
