# Generated by Django 5.2.5 on 2025-08-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_delete_newsimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourcontactphonenumber',
            name='our_contact',
        ),
        migrations.AddField(
            model_name='ourcontact',
            name='emails',
            field=models.JSONField(default='email@gmail.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourcontact',
            name='phone_numbers',
            field=models.JSONField(default='+998919653577'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OurContactEmail',
        ),
        migrations.DeleteModel(
            name='OurContactPhoneNumber',
        ),
    ]
