# Generated by Django 5.2.5 on 2025-09-01 14:16

import app.user.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_ourcontactphonenumber_our_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='images/banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'heif', 'heic', 'avif']), app.user.validations.check_image_size]),
        ),
    ]
