# Generated by Django 5.2.5 on 2025-09-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
    ]
